In [2]:
# numpy에서는 ndarray
# n-dimension array

#ndarray: n-dimension array
#Python의 List와 대동소이, 대신 ndarray는 같은 데이터 타입만 사용 가능
#List보다 메모리도 적게 사용하며 속도도 빠름

import numpy as np

In [64]:
a = [1, 2, 3, 4]
print("Python List: {0}, Type: {1}".format(a, type(a))) # 파이썬 리스트 생성
print("Python List Item: {0}, Type: {1}".format(a[0], type(a[0]))) 

# 리스트를 넘파이 배열로
arr = np.array(a)
print("Numpy Array: {0}, Type: {1}".format(arr, type(arr))) 
print("Numpy Array Item: {0}, Type: {1}".format(arr[0], arr.dtype)) 

arr2 = np.array([1, 3, "Hi", 3.14])
print("Numpy Array: {0}, Type: {1}".format(arr2, type(arr2))) 
print("Numpy Array Item: {0}, Type: {1}".format(arr2[0], arr2.dtype)) 

Python List: [1, 2, 3, 4], Type: <class 'list'>
Python List Item: 1, Type: <class 'int'>
Numpy Array: [1 2 3 4], Type: <class 'numpy.ndarray'>
Numpy Array Item: 1, Type: int32
Numpy Array: ['1' '3' 'Hi' '3.14'], Type: <class 'numpy.ndarray'>
Numpy Array Item: 1, Type: <U11


In [38]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
arr = np.array(a)
print("{0}차원의 array".format(arr.ndim))
print("차원의 개수와 원소의 개수: {0}".format(arr.shape))

arr.shape = 3, 5
arr

1차원의 array
차원의 개수와 원소의 개수: (15,)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# 적절한 코드를 이용하여 다음과 같이 출력하도록 작성

print(arr.shape)

for n in range(arr.shape[0]) :
    print("")
    for m in range(arr.shape[1]) :
        print("arr[{0}, {1}] = {2}".format(n, m, arr[n, m]), end = " ")

(4, 3)

arr[0, 0] = 1 arr[0, 1] = 2 arr[0, 2] = 3 
arr[1, 0] = 4 arr[1, 1] = 5 arr[1, 2] = 6 
arr[2, 0] = 7 arr[2, 1] = 8 arr[2, 2] = 9 
arr[3, 0] = 10 arr[3, 1] = 11 arr[3, 2] = 12 

In [85]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(arr.dtype)

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

arr = arr.astype(np.float64)
print(arr.dtype)


arr = np.array([1, 1.7, 3, 4.3, 5.6])
print(arr.dtype)

arr = arr.astype(np.int32) # 실수 -> 정수 변환시 소숫점은 버림
print(arr.dtype)
print(arr)

float64
int32
float64
float64
int32
[1 1 3 4 5]


In [89]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [104]:
# ndarray의 자주 사용되는 생성함수
arr = np.arange(0, 5, 0.3) # 시작, 끝, 간격
arr

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8])

In [111]:
# 주어진 범위를 지정한 샘플의 개수로 나누어 정해지는 간격으로 연속적인 배열 생성
# 간격: (끝-시작) / (샘플개수 -1)
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [124]:
arr = np.arange(12)
#arr.shape = 2,6
arr

arr1 = arr.reshape(4, 3)
arr1

arr[0] = 100 # arr과 베이스가 같음 (View)
arr1

if arr1.base is arr:
    print("데이터가 같다!")
    
# 데이터를 공유하지 않고 쉐입을 바꾸기
arr = np.arange(12)
arr1 = arr.reshape(4, 3).copy()

arr[0] = 100
arr1

if arr1.base is arr:
    print("데이터가 같다!")
else :
    print("다르다!")

데이터가 같다!
다르다!


In [135]:
# 기타 shape 조절 방법
arr = np.arange(0, 12, 1)
arr1 = arr.reshape(3, -1) # 무조건 3행, 열은 남은것 모두
arr1 = arr.reshape(-1, 2)
arr1

arr = np.arange(0, 100, 1).reshape(5, -1).copy()
arr = arr.ravel() # 모든 내용 1차원 배열로

In [147]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2 * 2
arr2 = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]]) # 3 * 3
arr3 = np.vstack((arr1, arr2))
arr4 = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 100]])
arr5 = np.hstack((arr1, arr4))

arr5

array([[  1,   2,   3,  11,  22,  33,  44,  55],
       [  4,   5,   6,  66,  77,  88,  99, 100]])

In [157]:
arr = np.arange(10, 20, 1)

for idx,data in enumerate(arr) :
    print("index: {0}, data: {1}".format(idx, data))

index: 0, data: 10
index: 1, data: 11
index: 2, data: 12
index: 3, data: 13
index: 4, data: 14
index: 5, data: 15
index: 6, data: 16
index: 7, data: 17
index: 8, data: 18
index: 9, data: 19


In [168]:
arr = np.arange(0, 5, 1)
arr1 = arr[0:2]
arr[-1:]
arr[0:2]

arr[0] = 1000
arr1 # Numpy 의 Slicing은 View다

array([1000,    1])

In [174]:
# Numpy Array의 연산
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

arr1 + arr2
arr1 * 3

array([ 3,  6,  9, 12])

In [193]:
# MovieLens Dataset
# Group Lens라는 미네소타 대학의 컴퓨터학과 연구실에서 수집한 영화 데이터
# 특정 영화에 대한 선호를 1~5사이의 실수로 높은 점수 일수록 선호도 높음

import numpy as np

data = np.loadtxt("data/movie/ratings.csv", delimiter=",", dtype=np.float64)
data.shape

print(data[:5, :])

[[1.00000000e+00 1.00000000e+00 4.00000000e+00 9.64982703e+08]
 [1.00000000e+00 3.00000000e+00 4.00000000e+00 9.64981247e+08]
 [1.00000000e+00 6.00000000e+00 4.00000000e+00 9.64982224e+08]
 [1.00000000e+00 4.70000000e+01 5.00000000e+00 9.64983815e+08]
 [1.00000000e+00 5.00000000e+01 5.00000000e+00 9.64982931e+08]]


In [216]:
# 모든영화의 전체 평균 평점
data[:,2].mean()

3.501556983616962

In [224]:
# 각 사용자별 평균 평점
user_ids = np.unique(data[:, 0])
user_ids.shape # 회원 수


result = []
for user_id in user_ids:
    data_for_user = data[data[:, 0] == user_id, :]
    mean_rating_for_user = data_for_user[:, 2].mean()
    result.append([user_id, mean_rating_for_user])
    
result = np.array(result)
result

array([[  1.        ,   4.36637931],
       [  2.        ,   3.94827586],
       [  3.        ,   2.43589744],
       ...,
       [608.        ,   3.13417569],
       [609.        ,   3.27027027],
       [610.        ,   3.68855607]])

In [5]:
import numpy as np
# 평균 평점이 가장 높은 영화의 제목을 출력하세요!
arr = np.arange(10, 22, 2)
arr[2]

arr[-3:] = 50
arr[:, 1].sum()

IndexError: too many indices for array